services:
  origin:
    image: airensoft/ovenmediaengine:0.16.8
    ports:
      - "1934-1935:1935/tcp" # RTMP Provider
      - "9998-9999:9999/udp" # SRT
    restart: always
    volumes:
      - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
    deploy:
      replicas: 2
      mode: vip

  edge:
    image: airensoft/ovenmediaengine:0.16.8
    ports:
      - "4333-4335:3333/tcp" # WebRTC Signaling / LLHLS
    restart: always
    volumes:
      - ./edge_conf:/opt/ovenmediaengine/bin/edge_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
    deploy:
      replicas: 3
      mode: vip

  nginx:
    image: openresty/openresty
    ports:
      - "8080:80/tcp"
    restart: always
    volumes:
      - ./nginx_conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
