services:
  origin:
    image: airensoft/ovenmediaengine:0.16.8
    ports:
      - "1934-1935:1935/tcp" # RTMP Provider
      - "9998-9999:9999/udp" # SRT
      - "8081-8082:8081" # API
    restart: always
    volumes:
      - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
    deploy:
      replicas: 2
      mode: vip

  updater:
    build:
      context: ./mapper
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - API_HOSTS=http://llhls-streaming-origin-1:8081,http://llhls-streaming-origin-2:8081
      - API_TOKEN=llhls-token
      - UPDATE_INTERVAL=5
      - STREAM_TTL=10
    depends_on:
      - origin
      - redis
    command: ./mapper updater

  api:
    build:
      context: ./mapper
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9090:8080"
    depends_on:
      - redis
    command: ./mapper api

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379-6379"
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: openresty/openresty
    ports:
      - "8080:80/tcp"
    restart: always
    volumes:
      - ./nginx_conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    depends_on:
      - updater
      - api

volumes:
  redis_data:
