services:
  origin:
    image: airensoft/ovenmediaengine:dev # temporary (OVT bug)
    ports:
      - "9000:9000/tcp" # OVT(Origin)
      - "1935:1935/tcp" # RTMP Provider
      - "9999:9999/udp" # SRT
      - "3333:3333/tcp" # WebRTC Signaling / LLHLS
      - "3478:3478/tcp" # WebRTC TURN
      - "10000-10004:10000-10004/udp" # WebRTC Candidate
    restart: always
    volumes:
      - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf

  edge:
    image: airensoft/ovenmediaengine:dev # temporary (OVT bug)
    ports:
      - "4333:3333/tcp" # WebRTC Signaling / LLHLS
      - "3479:3479/tcp" # WebRTC TURN
      - "10005-10009:10005-10009/udp" # WebRTC Candidate
    restart: always
    volumes:
      - ./edge_conf:/opt/ovenmediaengine/bin/edge_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
